name = "EnergyModelsFlex"
uuid = "a81b9388-333d-4b63-81f2-910b060b544c"
authors = ["Per Aaslid <per.aaslid@sintef.no>"]
version = "0.2.7"

[deps]
EnergyModelsBase = "5d7e687e-f956-46f3-9045-6f5a5fd49f50"
EnergyModelsRenewableProducers = "b007c34f-ba52-4995-ba37-fffe79fbde35"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
TimeStruct = "f9ed5ce0-9f41-4eaa-96da-f38ab8df101c"

[weakdeps]
EnergyModelsInvestments = "fca3f8eb-b383-437d-8e7b-aac76bb2004f"
EnergyModelsSDDP = "2d9f47c3-4e61-4511-b027-cb6f3cfb5b65"
SDDP = "f4570300-c277-11e8-125c-4912f86ce65d"

[extensions]
FlexInvestmentsExt = ["EnergyModelsInvestments"]
FlexSDDPExt = ["SDDP", "EnergyModelsSDDP"]

[compat]
EnergyModelsBase = "^0.8.1"
EnergyModelsRenewableProducers = "^0.6.4"
EnergyModelsInvestments = "^0.8.1"
EnergyModelsSDDP = "^0.1.9"
SDDP = "^1.10"
JuMP = "^1.23"
TimeStruct = "^0.9"
julia = "^1.10"